### ISSUE TITLE
Jump-to-definition doesn't work for external code.

### ISSUE THREAD

**Issue by MaikuMori** [sourcegraph/sourcegraph-atom#16]
The url which is opened in the browser is wrong.

Should be something like this:
> https://sourcegraph.com/github.com/mitsuhiko/flask@ec5811d0a15dc5ca2c5f231ac6aa79f9a107776e/.tree/flask/app.py#selected=67

Opened one is:
> https://sourcegraph.com/github.com/mitsuhiko/flask/PipPackage/Flask/.def/flask/app/Flask

**Comment by samertm** [comment]
That's a typo, it should be: https://sourcegraph.com/github.com/mitsuhiko/flask/.PipPackage/Flask/.def/flask/app/Flask (note the "." before "PipPackage"). The first route is for easily generating urls on the front end.

**Comment by MaikuMori** [comment]
This was fixed via 91bc55362ad3e89e1ae1622b5598de21aecfad2b.
