### ISSUE TITLE
Failed to detect git/hg repository root dir for "."; continuing. mkdir /.srclib-cache: permission denied

### ISSUE THREAD

**Issue by trashcan** [sourcegraph/sourcegraph-atom#23]
I get this error when I type alt-. in Atom:

/Users/me/go/bin/src api describe --file="/Users/me/go/src/gitrex.com/me/go-challenge-2/main.go" --start-byte=622 --no-examples: 2015/04/15 11:12:58 Failed to detect git/hg repository root dir for "."; continuing. mkdir /.srclib-cache: permission denied

I'm not sure why it's trying to create srclib cache at / ? 

I installed srclib and hg from brew, and sourcegraph-atom inside atom.  It doesn't seem to matter if I generate the srclib-cache myself or let the plugin build it. 

I tried setting some of the paths manually in settings but it didn't help:

  "sourcegraph-atom":
    goPath: "/Users/me/go"
    path: "/Users/me/go/bin"
    srcExecutablePath: "/Users/me/go/bin/src"

Any ideas?

**Comment by MaikuMori** [comment]
The directory you mentioned should be created in the projects directory and not `/`. Going to talk with sourcegraph guys and help getting it fixed upstream.

**Comment by trashcan** [comment]
This is fixed in 0.2.1. Thanks!
