### ISSUE TITLE
No references in this file.

### ISSUE THREAD

**Issue by taboularasa** [sourcegraph/sourcegraph-atom#3]
Not sure if this is an issue with my srclib installation, this editor plugin or if I'm just doing it all wrong but all I get is "No references in this file." or "No reference found under cursor." This is after sorting out a problem with the srclib-ruby tool not being able to install, but I think that's working now. See: https://github.com/sourcegraph/srclib-ruby/issues/1 It's not working for javascript files either so I'm inclined to think ruby is not the problem in this case. 

Is there something I need to do besides install srclib to use this editor plugin?

**Comment by MaikuMori** [comment]
Closing. 

This sounds like an issue with toolchain or your setup. Also a lot has changed in the plugin since then.

If you're still having problems feel free to open a new issue either here or upstream (at toolchain's repository)
