### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by ericwhyne** [sourcegraph/sourcegraph-atom#6]
Installed srclib and the atom plugin to have this happen when trying to view documentation and examples. 

Uncaught TypeError: Cannot read property 'trim' of undefined /home/eric/.atom/packages/sourcegraph-atom/lib/sourcegraph-atom.coffee:132
Uncaught TypeError: Cannot read property 'trim' of undefined sourcegraph-atom.coffee:95

**Comment by MaikuMori** [comment]
This probably is fixed with the last changes.

**Comment by samertm** [comment]
This works for me. @ericwhyne Can you check out sourcegraph-atom and see if you still have this issue? If you do, please reopen this.

**Comment by ericwhyne** [comment]
I'll do that. Thanks!
