### ISSUE TITLE
Sourcegraph: describe is unavailable

### ISSUE THREAD

**Issue by samertm** [sourcegraph/sourcegraph-atom#9]

**Comment by MaikuMori** [comment]
What do you mean? The keybind is `ctrl-alt-d` or right click an identifier and select `See Documentation and Examples`.

If src exiits with non-zero code while analyzing file then it won't shop up.

Here's how it look on some go code:

![describe](https://cloud.githubusercontent.com/assets/28470/6609693/863fecfa-c85d-11e4-894f-01150119daa1.png)

**Comment by samertm** [comment]
Ah, I didn't find it in the ctrl+shift+p menu. Do you see it there?

**Comment by MaikuMori** [comment]
It's there, try searching for `docs`.

Asctually I'll rename it so it's a bit easier to find. Also for some reason you can't find it searching for `sourcegraph`.
